apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow-k8s

spec:
  type: ClusterIP

  selector:
    app: airflow-webserver

  ports:
   - targetPort: 8080
     port: 8080


#Because you are using a Docker driver on darwin, the terminal needs to be open to run it.